###　利用环境变量统一管理接口测试前缀
### 文件名固定为： http-client.env.json
### 查询课程信息
POST {{content_host}}/content/course/list?pageNo=1&pageSize=3
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": "203001"
}

### 数据类型和 Json 参数之间一定要有一个行空行，否则无法请求


### 查询课程分类
GET {{content_host}}/content/course-category/list




# TODO ： 这是接口没有测试成功，需要再次测试
### 新增课程
POST http://localhost:8888/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 0,
  "originalPrice":100,
  "qq": "725482520",
  "wechat": "syhk",
  "phone": "10086",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "java 网络编程高级103",
  "pic": "fdsf",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "syhk java",
  "grade": "204001",
  "description": ""
}